export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "dark-card": "#17112B",
        "dark-bg": "#0F0A20",
        "surface-dim": "#dad9e2",
        "surface-container-high": "#e8e7f0",
        "secondary-container": "#795de4",
        "error": "#ba1a1a",
        "on-tertiary": "#ffffff",
        "on-surface": "var(--ink)",
        "on-tertiary-container": "#fffbff",
        "on-error-container": "#93000a",
        "on-secondary-container": "#fffbff",
        "surface-variant": "var(--surface-variant)",
        "background": "var(--bg)",
        "inverse-on-surface": "#f1f0f9",
        "secondary-fixed": "#e6deff",
        "primary-fixed": "#e6deff",
        "surface-container-low": "#f4f3fc",
        "primary-container": "var(--primary)",
        "light-bg": "#F0EFF8",
        "on-primary-container": "#ffffff",
        "outline-variant": "#c9c4d7",
        "on-primary-fixed-variant": "#481bc6",
        "outline": "#797586",
        "surface-bright": "#faf8ff",
        "on-secondary-fixed": "#1d0061",
        "surface": "var(--surface)",
        "tertiary-fixed-dim": "#ffb77b",
        "light-card": "#FFFFFF",
        "primary-fixed-dim": "#cabeff",
        "secondary": "#6042ca",
        "on-background": "var(--ink)",
        "inverse-surface": "#2f3037",
        "tertiary": "#8c4c00",
        "on-surface-variant": "var(--on-surface-variant)",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed-variant": "#6d3a00",
        "on-error": "#ffffff",
        "tertiary-container": "#b06000",
        "surface-container": "var(--surface-container)",
        "surface-tint": "var(--primary-dark)",
        "secondary-fixed-dim": "#cbbeff",
        "glass-overlay": "rgba(255, 255, 255, 0.4)",
        "on-secondary-fixed-variant": "#4a28b3",
        "on-tertiary-fixed": "#2e1500",
        "tertiary-fixed": "#ffdcc2",
        "on-secondary": "#ffffff",
        "on-primary-fixed": "#1c0062",
        "error-container": "#ffdad6",
        "inverse-primary": "#cabeff",
        "surface-container-highest": "#e2e1ea",
        "on-primary": "#ffffff",
        "primary": "var(--primary)",
        "dark-text": "#F0EEFF",
        "ongoing-color": "var(--ongoing-color, #3b82f6)",
        "halfdone-color": "var(--halfdone-color, #a67b5b)",
        "done-color": "var(--done-color, #10b981)",
        "danger-color": "var(--danger, #ba1a1a)"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "container-padding": "32px",
        "stack-gap": "12px",
        "sidebar-width": "256px",
        "margin-sm": "16px",
        "gutter-md": "24px"
      },
      fontFamily: {
        "display-lg": ["Plus Jakarta Sans"],
        "label-md": ["Plus Jakarta Sans"],
        "body-md": ["Plus Jakarta Sans"],
        "body-lg": ["Plus Jakarta Sans"],
        "headline-md": ["Plus Jakarta Sans"],
        "title-lg": ["Plus Jakarta Sans"],
        "headline-lg": ["Plus Jakarta Sans"],
        "headline-lg-mobile": ["Plus Jakarta Sans"]
      },
      fontSize: {
        "display-lg": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "title-lg": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "700" }]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
}
